### ISSUE TITLE
Exception when loosing broker connection

### ISSUE THREAD

**Issue by ckrey** [jpmens/ypom-cli#3]
'''
$ ./ypom-cli.py
...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/Library/Python/2.7/site-packages/paho/mqtt/client.py", line 2091, in _thread_main
    self.loop_forever()
  File "/Library/Python/2.7/site-packages/paho/mqtt/client.py", line 1188, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/Library/Python/2.7/site-packages/paho/mqtt/client.py", line 790, in loop
    self._sockpairR.recv(1)
error: [Errno 35] Resource temporarily unavailable

```
```

**Comment by jpmens** [comment]
Yes, I need to take some time to evaluate this for a whole bunch of tools, so I'll get to it.
